{{- $ns := .Values.global.namespace }}
{{- $rel := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: alertmanager }
  template:
    metadata:
      labels: { app: alertmanager }
    spec:
      containers:
        - name: alertmanager
          image: {{ .Values.alertmanager.image }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/data"
          ports:
            - { name: web, containerPort: 9093 }
          volumeMounts:
            - { name: config, mountPath: /etc/alertmanager }
            - { name: data,   mountPath: /data }
      volumes:
        - name: config
          configMap: { name: alertmanager-config }
        - name: data
          persistentVolumeClaim:
            claimName: {{ $rel }}-alertmanager-data
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ $ns }}
spec:
  selector: { app: alertmanager }
  ports:
    - { name: web, port: 9093, targetPort: 9093 }
