{{- $ns := .Values.global.namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ $ns }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prom
        type: prometheus
        access: proxy
        url: http://prometheus.{{ $ns }}.svc:9090
        isDefault: true
        jsonData:
          timeInterval: "15s"
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.{{ $ns }}.svc:3100
        jsonData: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ $ns }}
data:
  grafana.ini: |
    [security]
    admin_user = {{ .Values.grafana.adminUser }}
    admin_password = {{ .Values.grafana.adminPassword }}
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/sre-application-overview.json
