apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prom
        type: prometheus
        access: proxy
        url: http://prometheus.{{ .Values.monitoring.namespace }}.svc:9090
        isDefault: true
        jsonData:
          timeInterval: "15s"
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.{{ .Values.monitoring.namespace }}.svc:3100
        jsonData: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.monitoring.namespace }}
data:
  grafana.ini: |
    [server]
    # root_url can be set if needed for ingress/route
    [security]
    admin_user = {{ .Values.grafana.adminUser }}
    admin_password = {{ .Values.grafana.adminPassword }}
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/sre-application-overview.json
