apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.monitoring.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ["{{ .Values.prometheus.alertmanager.serviceName }}.{{ .Values.monitoring.namespace }}.svc:{{ .Values.prometheus.alertmanager.port }}"]

    rule_files:
      - /etc/prometheus/rules/*.yml

    scrape_configs:
      # Kubernetes pod scraping based on annotations
      - job_name: 'kubernetes-pods-annotated'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: "(.+)"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: "(.+)"
            replacement: "$1"
          - source_labels: [__address__, __meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ".*;(.*);(.*)"
            replacement: "$1:$2"
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.*)
        {{- if .Values.prometheus.scrape.additionalScrapeConfigs }}
      {{- toYaml .Values.prometheus.scrape.additionalScrapeConfigs | nindent 6 }}
        {{- end }}

  instance-down.yml: |
    groups:
      - name: basic-alerts
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Target instance is down"
              description: "Prometheus target {{ $labels.instance }} has been down for over 1 minute."
